theme: jekyll-theme-leap-day
exclude: [
  docker-compose.yml,
  .gitignore
]
plugins:
  - jekyll-seo-tag
# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
# highlighter: pygments
