url: https://vild124.github.io
title: プログラミングとかLinuxとかの備忘録
subtitle: ""
name: Vild
description: プログラミング、Linuxでハマった箇所や環境構築のメモ

theme: jekyll-theme-leap-day
exclude: [
  docker-compose.yml,
  .gitignore
]
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
# highlighter: pygments
